version: '2'
networks:
  default:
    external:
      name: base_project
services:
  nginx:
    build: Docker/Nginx
    depends_on:
      #- angular
      - python
    volumes_from:
      #- angular
      - python
    volumes:
      #- ./Docker/Nginx/FrontEnd.conf:/etc/nginx/conf.d/FrontEnd.conf
      - ./Docker/Nginx/Backend.conf:/etc/nginx/conf.d/Backend.conf
    ports:
      - 80:80
    links:
       - "python"
  python:
    build: Backend/
    volumes:
      - ./:/var/www/backend
    volumes_from:
      - hots
    depends_on:
      - hots
    #command: ["--yaml", "wsgi_config.yml"]
    #command: --http :9090 --wsgi-file wsgi.py
  hots:
    build: Hots/
    volumes:
      - ./HotsOutput:/hots_output
#  angular:
#    build: FrontEnd/
#    command: "build --watch"
#    volumes:
#      - ./Frontend:/var/www/html/frontend
