version: '2'
networks:
  default:
    external:
      name: base_project
services:
  nginx:
    image: nginx:latest
    depends_on:
      - angular
      - python
    volumes_from:
      - angular
      - python
    volumes:
      - ./Docker/Nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
       - "python"
  python:
    build: Backend/
    volumes:
      - ./Backend:/var/www/backend
    volumes_from:
      - hots
    depends_on:
      - hots
  hots:
    build: Hots/
    volumes:
      - ./HotsOutput:/hots_output

  angular:
    build: FrontEnd/
    command: "--watch"
    volumes:
      - ./Frontend/e2e:/var/www/frontend/e2e
      - ./Frontend/src:/var/www/frontend/src
      - ./Frontend/protractor.conf.js:/var/www/frontend/protractor.conf.js
      - ./Frontend/tsconfig.conf.js:/var/www/frontend/tsconfig.conf.js
      - ./Frontend/tslint.conf.js:/var/www/frontend/tslint.conf.js
